ofile_template: 'cf_%l.csv'

collections:
  met:
    template: 'https://opendap.nccs.nasa.gov/dods/gmao/geos-cf/assim/met_tavg_1hr_g1440x721_x1'
    template_forecast: 'https://opendap.nccs.nasa.gov/dods/gmao/geos-cf/assim/met_tavg_1hr_g1440x721_x1'
    vars:
      ps:
        name_in_file: 'ps'
      t10m:
        name_in_file: 't10m'
  
  chem:
    template: 'https://opendap.nccs.nasa.gov/dods/gmao/geos-cf/assim/chm_tavg_1hr_g1440x721_v1' 
    template_forecast: 'https://opendap.nccs.nasa.gov/dods/gmao/geos-cf/assim/chm_tavg_1hr_g1440x721_v1' 
    vars: 
      o3:
        name_in_file: 'o3'
        scal: 1.0e+9
      no2:
        name_in_file: 'no2'
        scal: 1.0e+9
      co:
        name_in_file: 'co'
        scal: 1.0e+9
      pm25_gcc:
        name_in_file: 'pm25_rh35_gcc'
        scal: 1.0
      pm25_gocart:
        name_in_file: 'pm25_rh35_gocar'
        scal: 1.0e+9
